/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Telas.Cadastro;

import org.example.Controller.Paciente.ContatoController;
import org.example.Controller.Paciente.EnderecoController;
import org.example.Controller.Paciente.PacienteController;
import org.example.Model.Paciente.Contato.Contato;
import org.example.Model.Paciente.Contato.TipoContato;
import org.example.Model.Paciente.Endereco.Cidade;
import org.example.Model.Paciente.Endereco.Endereco;
import org.example.Model.Paciente.Endereco.Uf;
import org.example.Model.Paciente.Paciente;

import javax.swing.*;
import java.sql.Date;
import java.util.List;

/**
 *
 * @author winter
 */
public class tela_cadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form tela_cadastroPaciente
     */
    public tela_cadastroPaciente() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputDatanascimento = new javax.swing.JTextField();
        inputContato = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boxTipoContato = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        inputRua = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputCidade = new javax.swing.JTextField();
        boxCidade = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        inputEstado = new javax.swing.JTextField();
        boxEstado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        inputNumeroCasa = new javax.swing.JTextField();
        btnCadastroPaciente = new javax.swing.JButton();
        inputTipoContato = new javax.swing.JTextField();



        jLabel1.setText("Nome");

        jPanel2.setBackground(new java.awt.Color(206, 6, 147));
        jPanel2.setForeground(new java.awt.Color(202, 6, 147));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastrar Paciente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel3.setText("CPF");

        jLabel4.setText("Data Nascimento (YYYY-MM-DD)");

        inputDatanascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDatanascimentoActionPerformed(evt);
            }
        });

        jLabel5.setText("Contato");

        jLabel6.setText("Tipo de Contato");
        ContatoController contatoController = new ContatoController();
        List<TipoContato> tipoContatos = contatoController.getAllTiposContatos();
        String[] arrayTiposContatos = new String[tipoContatos.size()];
        for (int i = 0; i < tipoContatos.size(); i++) {
            arrayTiposContatos[i] = tipoContatos.get(i).getTipo();
        }

        boxTipoContato.setModel(new javax.swing.DefaultComboBoxModel<>(arrayTiposContatos));
        boxTipoContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoContatoActionPerformed(evt);
            }
        });

        jLabel7.setText("Rua");

        jLabel8.setText("Cidade");
        EnderecoController enderecoController = new EnderecoController();
        List<Cidade> cidades = enderecoController.getAllCidade();
        String[] arrayCidades = new String[cidades.size()];
        for (int i = 0; i < cidades.size(); i++) {
            arrayCidades[i] = cidades.get(i).getNome();
        }

        boxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(arrayCidades));
        boxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCidadeActionPerformed(evt);
            }
        });

        jLabel9.setText("Estado");
        List<Uf> ufs = enderecoController.getAllUf();
        String[] arrayUfs = new String[ufs.size()];
        for (int i = 0; i < ufs.size(); i++) {
            arrayUfs[i] = ufs.get(i).getSigla();
        }
        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(arrayUfs));
        boxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEstadoActionPerformed(evt);
            }
        });

        jLabel10.setText("Numero da Casa");

        inputNumeroCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumeroCasaActionPerformed(evt);
            }
        });

        btnCadastroPaciente.setText("Cadastrar Paciente");
        btnCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputNumeroCasa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputCPF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boxCidade, 0, 124, Short.MAX_VALUE))
                                    .addComponent(inputRua, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9)
                                .addComponent(inputContato)
                                .addComponent(inputDatanascimento)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(inputEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(inputTipoContato))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(boxTipoContato, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(boxEstado, javax.swing.GroupLayout.Alignment.TRAILING, 0, 100, Short.MAX_VALUE))))
                            .addComponent(btnCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDatanascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTipoContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTipoContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastroPaciente))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputDatanascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDatanascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDatanascimentoActionPerformed

    private void inputNumeroCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumeroCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumeroCasaActionPerformed

    private void btnCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPacienteActionPerformed
        if (inputCidade.getText().isEmpty() || inputEstado.getText().isEmpty() || inputRua.getText().isEmpty() ||
                inputNumeroCasa.getText().isEmpty() || inputNome.getText().isEmpty() || inputCPF.getText().isEmpty() ||
                inputDatanascimento.getText().isEmpty() || inputContato.getText().isEmpty() || inputTipoContato.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            PacienteController pacienteController = new PacienteController();
            EnderecoController enderecoController = new EnderecoController();
            ContatoController contatoController = new ContatoController();

            Cidade novaCidade = new Cidade();
            novaCidade.setNome(inputCidade.getText());

            Uf novoUf = new Uf();
            novoUf.setSigla(inputEstado.getText());

            Endereco novoEndereco = new Endereco();
            novoEndereco.setRua(inputRua.getText());
            novoEndereco.setNumero(inputNumeroCasa.getText());
            novoEndereco.setCidade(novaCidade);
            novoEndereco.getCidade().setUf(novoUf);
            enderecoController.addEndereco(novoEndereco);

            Paciente novoPaciente = new Paciente();
            novoPaciente.setNome(inputNome.getText());
            novoPaciente.setCpf(inputCPF.getText());
            novoPaciente.setData_nascimento(Date.valueOf(inputDatanascimento.getText()));
            novoPaciente.setEndereco(novoEndereco);

            Contato novoContato = new Contato();
            novoContato.setInformacao(inputContato.getText());

            TipoContato novoTipoContato = new TipoContato();
            novoTipoContato.setTipo(inputTipoContato.getText());

            novoContato.setTipoContato(novoTipoContato);
            contatoController.addContato(novoContato);
            novoPaciente.setContato(novoContato);

            pacienteController.addPaciente(novoPaciente);
            this.dispose();
        }

    }//GEN-LAST:event_btnCadastroPacienteActionPerformed

    private void boxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEstadoActionPerformed
        
        String selectedOption = (String) boxEstado.getSelectedItem();


        if (selectedOption.equals(null) || selectedOption.equals("")) {
            inputEstado.setText("");
            inputEstado.setEnabled(false);
        } else {
            inputEstado.setText(selectedOption);
            inputEstado.setEnabled(true);
        }


    }//GEN-LAST:event_boxEstadoActionPerformed

    private void boxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCidadeActionPerformed
        String selectedOption = (String) boxCidade.getSelectedItem();


        if (selectedOption.equals(null) || selectedOption.equals("")) {
            inputCidade.setText("");
            inputCidade.setEnabled(false);
        } else {
            inputCidade.setText(selectedOption);
            inputCidade.setEnabled(true);
        }

    }//GEN-LAST:event_boxCidadeActionPerformed

    private void boxTipoContatoActionPerformed(java.awt.event.ActionEvent evt) {
        String selectedOption = (String) boxTipoContato.getSelectedItem();


        if (selectedOption.equals(null) || selectedOption.equals("")) {
            inputTipoContato.setText("");
            inputTipoContato.setEnabled(false);
        } else {
            inputTipoContato.setText(selectedOption);
            inputTipoContato.setEnabled(true);
        }

    }
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCidade;
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JComboBox<String> boxTipoContato;
    private javax.swing.JButton btnCadastroPaciente;
    private javax.swing.JTextField inputCPF;
    private javax.swing.JTextField inputCidade;
    private javax.swing.JTextField inputContato;
    private javax.swing.JTextField inputDatanascimento;
    private javax.swing.JTextField inputEstado;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputNumeroCasa;
    private javax.swing.JTextField inputRua;
    private javax.swing.JTextField inputTipoContato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
